name: default
run-name: ${{ github.actor }} generating backend 🚀

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:    
        - name: List files in the repository
          run: actions/checkout@v3
        - name: generate data.js
          run: python pkg/data.py
